version: "3.7"

services:
  #контейнер
  server:
    #образ
    image: c1f223550027
    #команда после создания образа
    environment:
      db_name: 'db'
    ports:
        - 8080:8080

    depends_on:
        - db

  db:
    image:  284c2de2c6b4
    command:
      [
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci'
      ]
    environment:
      db_name: 'db'
      DB_USER: root
      DB_PASSWORD: my-secret-pw
    #контейнер может обращаться к 'localhost' компьютера
    network_mode: host
   # entrypoint: ["./docker-entrypoint.sh"]

