version: "3.7"

services:

  server:

    image: 4ff1f188499c
    environment:
      db_name: '10.11.13.194'
    ports:
        - 23306:23306
    depends_on:
        - db

  db:
    image:  distance-calculator-db:latest
    environment:
      db_name: 'db'
      DB_USER: root
      DB_PASSWORD: my-secret-pw
      MYSQL_ROOT_PSSWORD: my-secret-pw
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
      MYSQL_RANDOM_ROOT_PASSWORD: my-secret-pw
    ports:
      - 13306:3306

